### ISSUE TITLE
Need fast script to check single node against existing hubs and supernodes

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/apps-script#2]
The full links is getting too dense and slow to load when trying to quickly figure out LoS. I'm thinking we should have another "Links" tab for line of sight name say "Scratch" that only has supernodes and hubs. It refers to the main spreadsheet so no need to enter any info.

The problem with the tab pairs is that you have to enter the existing nodes all over again. This new "Scratch" tab would only link nodes that are in the main "Form Responses 1" tab

**Comment by jessetane** [comment]
Makes sense, I like the "multiple links tabs, single nodes tab" direction
