### ISSUE TITLE
Remove shadow under links

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/apps-script#3]
On google earth the shadows under the links are so dense that sometimes it hides the other links. Is there a way to remove this or toggle it on and off?

**Comment by jessetane** [comment]
yeah, i think the problem is related to the order in which the surfaces are drawn, i remember looking at this a while ago and not finding a good solution but i will revisit

**Comment by bhny** [comment]
fixed a while ago (by Olivier I think)
